UPSTREAM: mt76: mt7615: fix potential overflow on large shift
Fix the following static checker warning:
error: undefined (user controlled) shift '(((1))) << (c->omac_idx)'

Fixes: 402a695b1ae6 ("mt76: mt7615: fix CSA notification for DBDC")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Ryder Lee <ryder.lee@mediatek.com>
Signed-off-by: Felix Fietkau <nbd@nbd.name>
(cherry picked from commit 3253f8fddd954aba9ac88ce3c34551dcca505b21
 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git master)

BUG=b:178754244, b:188614537
TEST=Merge patch from upstream

Signed-off-by: Sean Wang <objelf@gmail.com>
Change-Id: Id3b198f934f782a0b203bc89b1e6d0bc24954a15