FROMGIT: Bluetooth: btusb: Fix application of sizeof to pointer
The coccinelle check report:
"./drivers/bluetooth/btusb.c:2239:36-42:
ERROR: application of sizeof to pointer".
Using the real size to fix it.

Fixes: 5a87679ffd443 ("Bluetooth: btusb: Support public address configuration for MediaTek Chip.")
Reported-by: Zeal Robot <zealci@zte.com.cn>
Signed-off-by: David Yang <davidcomponentone@gmail.com>
Signed-off-by: Marcel Holtmann <marcel@holtmann.org>
(cherry picked from commit dc1650fc94a8566fb89f3fd14a26d1cec7865f16
 https://git.kernel.org/pub/scm/linux/kernel/git/bluetooth/bluetooth-next.git master)

BUG=b:178754244, b:188614537
TEST=build on cherry

Signed-off-by: Sean Wang <objelf@gmail.com>
Change-Id: I97552a130394770d9066e10725b68bb722c1d296